global using IdeaTech.SemanticKernel.Connectors.Hunyuan;
global using Microsoft.Extensions.Logging;
global using Microsoft.SemanticKernel.Services;
global using Moq;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using TencentCloud.Common;
global using TencentCloud.Common.Profile;
global using TencentCloud.Hunyuan.V20230901;
global using TencentCloud.Hunyuan.V20230901.Models;
global using Xunit;
global using TestConstants = SemanticKernel.Connectors.Hunyuan.UnitTests.HunyuanTestHelper.Constants;
